- E steps

    Given $\mu_k$ (class means), (1) calculate the distance between $\mu_k$ and all data (2) sort the distance (3) assign "class label" $r_{nk}$

- M steps

    Given $r_{nk}$, calculate $\mu_k$ for each class

In [52]:
import numpy as np

def distance_function(class_means, data):
    
    # class_means: [K, D] 
    # data: [N, D]
    # calculate the distance between each data point and class means
    # return the distance as [N, K] each row is the distance between a data points and all class 
    
    K, D = class_means.shape
    N, _ = data.shape
    
    class_means = class_means.reshape(1, K, D)
    data = data.reshape(N, 1, D)
    
    distance = np.sqrt(np.sum((data - class_means)**2, axis = 2))
    
    return distance


def E_step(class_means, distance_function, data, K):
    
    # given class mean, calculate class assignment
    # class_means: [K, D] 
    # data: [N, D]
    
    distance = distance_function(class_means, data) # [N, K]
    
    N, D = data.shape
    
    closest_class = distance.argmin(1) # log closest class index for each data

    class_assignment = np.zeros((N, K))
    
    for datapoint_index, datapoint_assignment in enumerate(class_assignment):
        cur_class_assignment = closest_class[datapoint_index]
        datapoint_assignment[cur_class_assignment] = 1
    
    return class_assignment

def M_step(class_assignment, data, K):
    # data: [N, D]
    # class_assignment: [N, K] note that the k-th column indicates whether each data points belongs to class k
    
    N, D = data.shape

    class_means = np.zeros((K, D))
    
    for k in range(K):
        k_class_assignment = class_assignment[:, k].reshape(N, 1)
        k_class_mean = np.sum(data * k_class_assignment, axis=0) # [N, D] * [N, 1] -> [N, D]
        class_means[k] = k_class_mean
    
    return class_means

def k_means(data, K, steps):
    
    N, D = data.shape
    
    class_means = np.random.random((K, D))

    for step in range(steps):
        class_assignment = E_step(class_means, distance_function, data, K)
        class_means = M_step(class_assignment, data, K)
    
    return class_assignment, class_means
    
    
    

In [53]:
points = [[1, 2], [2, 3], [3, 4], [8, 9], [9, 10]]
k = 2  # Number of clusters


In [56]:
k_means(np.array(points), k, 20)

(array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]),
 array([[23., 28.],
        [ 0.,  0.]]))

In [57]:
from sklearn.cluster import KMeans

In [60]:
kmeans = KMeans(n_clusters=2).fit(np.array(points))

In [61]:
kmeans.labels_

array([1, 1, 1, 0, 0], dtype=int32)

In [62]:
kmeans.cluster_centers_

array([[8.5, 9.5],
       [2. , 3. ]])